apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bootcamp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bootcamp
  template:
    metadata:
      labels:
        app: k8s-bootcamp
    spec:
      containers:
        - name: k8s-bootcamp
          image: gcr.io/google-samples/kubernetes-bootcamp:v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bootcamp
  template:
    metadata:
      labels:
        app: k8s-bootcamp
    spec:
      containers:
        - name: echo
          image: mendhak/http-https-echo
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-bootcamp
  namespace: default
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: k8s-bootcamp
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: k8s-bootcamp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-bootcamp
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - hosts:
        # Change this to your own hostname
        - kuber.morjoff.com
        - rss.morjoff.com
      secretName: letsencrypt-prod
  rules:
    # Change this to your own hostname
    - host: kuber.morjoff.com
      http:
        paths:
          - path: /
            backend:
              serviceName: k8s-bootcamp
              servicePort: http
    - host: rss.morjoff.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echo
              servicePort: http
